# Generated by Django 3.2.9 on 2022-06-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Mult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('description', models.TextField()),
                ('season_num', models.IntegerField()),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Мультик',
                'verbose_name_plural': 'Мультики',
            },
        ),
        migrations.CreateModel(
            name='All_Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_num', models.IntegerField()),
                ('photo', models.ImageField(upload_to='static/img')),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('mult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.all_mult')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Long_Mult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.all_mult')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='All_Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.all_season')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
