# Generated by Django 3.2.9 on 2022-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220622_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_mult',
            name='URL',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='all_series',
            name='series_num',
            field=models.IntegerField(null=True),
        ),
    ]
